version: '2.1'

services:

  users-service:
    container_name: extracts_ms
    build: .
    volumes:
      - '.:/home/diego/Documentos/ms/flask-microservices-users'
    ports:
      - 3004:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
